export const expenseActionTypes = {
    ADD_EXPENSE: 'ADD_EXPENSE',
    EDIT_EXPENSE: 'EDIT_EXPENSE',
    GET_EXPENSES: 'GET_EXPENSES',
    GOT_EXPENSES: 'GOT_EXPENSES',
    REMOVE_EXPENSE: 'REMOVE_EXPENSE',
    START_ADD_EXPENSE: 'START_ADD_EXPENSE',
    START_EDIT_EXPENSE: 'START_EDIT_EXPENSE',
    START_REMOVE_EXPENSE: 'START_REMOVE_EXPENSE',
}

export const filterActionTypes = {
    SET_END_DATE: 'SET_END_DATE',
    SET_START_DATE: 'SET_START_DATE',
    SET_TEXT_FILTER: 'SET_TEXT_FILTER',
    SORT_BY_AMOUNT: 'SORT_BY_AMOUNT',
    SORT_BY_DATE: 'SORT_BY_DATE'
}