export const expenseActionTypes = {
    ADD_EXPENSE: 'ADD_EXPENSE',
    EDIT_EXPENSE: 'EDIT_EXPENSE',
    REMOVE_EXPENSE: 'REMOVE_EXPENSE'
}

export const filterActionTypes = {
    SET_END_DATE: 'SET_END_DATE',
    SET_START_DATE: 'SET_START_DATE',
    SET_TEXT_FILTER: 'SET_TEXT_FILTER',
    SORT_BY_AMOUNT: 'SORT_BY_AMOUNT',
    SORT_BY_DATE: 'SORT_BY_DATE'
}